/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\Users\Raul\Dropbox\UAS\SSNS\workspace\ble_sdk_2_02_02_25\blelib\host\host_pxxx.a"
"C:\Users\Raul\Dropbox\UAS\SSNS\workspace\ble_sdk_2_02_02_25\blelib\ctrl\cc2640\cc2640_ctrl_pxxx.a"
"C:\Users\Raul\Dropbox\UAS\SSNS\workspace\ble_sdk_2_02_02_25\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none.a"
